{% set name = "fire" %}
{% set version = "0.2.1" %}
{% set sha256 = "6865fefc6981a713d2ce56a2a2c92c56c729269f74a6cddd6f4b94d16ae084c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - termcolor
    - six

test:
  imports:
    - fire

about:
  home: https://github.com/google/python-fire
  license: Apache-2
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Fire is a library for creating command line interfaces (CLIs) from absolutely any Python object.'
  description: |
    Python Fire is a simple way to create a CLI in Python. Python Fire is a helpful tool for developing and debugging Python code. Python Fire helps with exploring existing code or turning other people's code into a CLI. Python Fire makes transitioning between Bash and Python easier. Python Fire makes using a Python REPL easier by setting up the REPL with the modules and variables you'll need already imported and created.
  doc_url: https://github.com/google/python-fire/blob/master/doc/guide.md
  dev_url: https://github.com/google/python-fire

extra:
  recipe-maintainers:
    - CJ-Wright
    - dougalsutherland
