{% set name = "fire" %}
{% set version = "0.4.0" %}
{% set sha256 = "c5e2b8763699d1142393a46d0e3e790c5eb2f0706082df8f647878842c216a62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - termcolor
    - six

test:
  commands:
    - pip check
  imports:
    - fire
  requires:
    - pip

about:
  home: https://github.com/google/python-fire
  license: Apache-2
  license_family: Apache
  license_file: LICENSE
  summary: Python Fire is a library for creating command line interfaces (CLIs) from absolutely any Python object.
  description: |
    Python Fire is a simple way to create a CLI in Python. Python Fire is a helpful tool for developing and debugging Python code. Python Fire helps with exploring existing code or turning other people's code into a CLI. Python Fire makes transitioning between Bash and Python easier. Python Fire makes using a Python REPL easier by setting up the REPL with the modules and variables you'll need already imported and created.
  doc_url: https://github.com/google/python-fire/blob/master/docs/guide.md
  dev_url: https://github.com/google/python-fire

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for `streamai
    recipe-maintainers:
      - ianaobi
  recipe-maintainers:
    - CJ-Wright
