# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Y7WB0DGgeaigvGHoeMcJzf2EfJSXFSe8sXKmwQPNChAHgRKnsaV6qJ4o+hxEQK7vOeSgf6z8lTvWfCvwOzfi1QrF/Diw+YEvh5GhAcgjjpqDm0dSR5CAqie9nmj0vRSLO0BJWgdSR8rdNK++PrW3xqfoWsEXY1LGVhwaIiMP9Z4Mwn0UERS3YfiR5GuQkF/sA/YOMVyrQK7UGUz2mccwZhJwfNUemuiNvxmE10xrUIkD+wdRSS8XQ4stfRTKE9GykU/214n5kZxSm6xIVf3Oz+Ijjf02try0gCNoSmZdGlMgzgsp6HAqO5rpakPFHr/VTv+nh0HuQ/IYB6wu+kYp4mXZlhtAb0gwLdPkoMWp0VMybD9UZrovObkyjAhCuHBnWPj3MHArNtbqS3u78FjJqTTF9CZX06QEO0cqJdlBldNr42i+THp7H6qSY0Swjxc82UYRlJfwQWWeD6cO5zK9ptYjMUZBQCtfBWiPx12KzXD9bj3lOsKZsD55crw2p3GirfKmdqpri5UACCz3+GZgMVqIJdNMTs/qimo9obNTyWt/WkLOVrvXs+1QJgNPHU4Q5dELoYYUAJ9dPrbCYn9SxBlPUMtAiZlqWBeDee5SDfjJq4Iq27Zsa//hS2eGSaF0vbG6zYQsZcIQMLvWPvqRLwjv2UcLwCJPXiH6xEOYDLc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
