travis:
  secure:
    BINSTAR_TOKEN: Y7WB0DGgeaigvGHoeMcJzf2EfJSXFSe8sXKmwQPNChAHgRKnsaV6qJ4o+hxEQK7vOeSgf6z8lTvWfCvwOzfi1QrF/Diw+YEvh5GhAcgjjpqDm0dSR5CAqie9nmj0vRSLO0BJWgdSR8rdNK++PrW3xqfoWsEXY1LGVhwaIiMP9Z4Mwn0UERS3YfiR5GuQkF/sA/YOMVyrQK7UGUz2mccwZhJwfNUemuiNvxmE10xrUIkD+wdRSS8XQ4stfRTKE9GykU/214n5kZxSm6xIVf3Oz+Ijjf02try0gCNoSmZdGlMgzgsp6HAqO5rpakPFHr/VTv+nh0HuQ/IYB6wu+kYp4mXZlhtAb0gwLdPkoMWp0VMybD9UZrovObkyjAhCuHBnWPj3MHArNtbqS3u78FjJqTTF9CZX06QEO0cqJdlBldNr42i+THp7H6qSY0Swjxc82UYRlJfwQWWeD6cO5zK9ptYjMUZBQCtfBWiPx12KzXD9bj3lOsKZsD55crw2p3GirfKmdqpri5UACCz3+GZgMVqIJdNMTs/qimo9obNTyWt/WkLOVrvXs+1QJgNPHU4Q5dELoYYUAJ9dPrbCYn9SxBlPUMtAiZlqWBeDee5SDfjJq4Iq27Zsa//hS2eGSaF0vbG6zYQsZcIQMLvWPvqRLwjv2UcLwCJPXiH6xEOYDLc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
