travis:
  secure:
    BINSTAR_TOKEN: k+rEHvF+qlfOuAF1jOFM22CHfs+d1NH3nxRWzUOuwTERoy6xjReAtxH6BVR3iCuBFPXL8Sejj3YNJqs83tCll6f3kpFFnWnr7et1oN7cw1GSbco5czBwzqmLt+wsuE7hBQwTrELIi+BqH/7pHGJCkgYgSIIU8sISjm77BLtrrtxbl68M8J5zPK8WTXsNlgmc4E4dBdeoy6MsgPMp8xVy/GQDlOzUV3K3Ostr1XIgjIqPv4pWuzNZk2jPjWEWt2wFTksQFKreROWGDRfM72lM0lZWFZctxFKDyhtdqkUMxyKRIuq46Airqywg1ZQdE4FmcwrFBauBRSr+dPt/vAx5PfiMyIfRrAlBHDSQ6RcjR06Eq+kZ6rhddidTof4AsIAfC4FJT4Wa9lzSfwCVEnhLlQMpyeeOJ4DqJAWQh7PTS0Kx+UnhQMBy5cl6Zjkf21a3HV6FHg4zbSayhadHteSpZs2+dZbizStjuP1+apr1PpvP4X9+bYa9YfiLJYpwYBfTlpxY1OYLJlU9Mlv6d7IhZfyigDxy39FrkUtwAJPdy4z/92KtiklNKzQQpOM7VlkhudYO3tYjdUbA6doMfOtbp6vugX6HlkXKciMKswECRjqUBBiaj7zxl+ORyDftOAYS8y0r64XUMw+BAzagmWuK1/FlgY8j0XejyfbDfEUjnY4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
